### ISSUE TITLE
text overflow in mobile view in coverage

### ISSUE THREAD

**Issue by SusheelThapa** [locus-ioe/CIT-MAP#16]
![image](https://github.com/user-attachments/assets/92a3307e-6c2b-46e0-8af3-e2a131c6051e)

File: https://github.com/locus-ioe/CIT-MAP/blob/032cb628ff138a2bc6c8e8cab424b6678f511790/src/components/province/ProvinceAbout.tsx#L26C2-L48C11

Task
- [ ] Make the component responsive so that text doesn't overflow

**Comment by naufandarmawan** [comment]
Hi! 👋
I’d love to contribute to this issue. Could you please share if there’s a preferred approach or guideline you’d like me to follow to make the component responsive? For example, should I use just make the font size smaller for certain breakpoint?

Thank you! 😊

**Comment by SusheelThapa** [comment]
@naufandarmawan  Thank you for you time.

Currently, in this project we donot have any such breakpoint, we have just design the project for Desktop and Mobile.

For this issue, you just need to adjust the size of the font.
