### ISSUE TITLE
feat: Showing the bigger image while clicking

### ISSUE THREAD

**Issue by SusheelThapa** [locus-ioe/CIT-MAP#6]
![image](https://github.com/user-attachments/assets/5a7d1996-509f-4c27-9f31-debea7cd4ddf)
Task to do:

- [ ] When we click on the images then the image should be shown in the bigger versiion

For examples

Kinda like this one,
![image](https://github.com/user-attachments/assets/4d54c2ef-7765-489f-8c36-e89984eb75e2)

**Comment by itmaybehimm** [comment]
Leave it to me
