### ISSUE TITLE
perf: SEO Enhancement

### ISSUE THREAD

**Issue by SusheelThapa** [locus-ioe/CIT-MAP#7]

**Comment by Ujj1225** [comment]
@SusheelThapa  I'd like to work on this

**Comment by Ujj1225** [comment]
@SusheelThapa 
This is the plan outline that I am considering. If there is anything I should add or remove, please let me know. Currently, I am thinking of improving the SEO by:

- Generating a Sitemap: I will create a sitemap to provide search engines with a clear structure all of website's pages, making it easier for them to index my content effectively.
- Adding Robots.txt: I will add a robots.txt file to guide search engines on which parts of my website they should crawl and index, giving me better control over 
- Adding Meta Tags: I will include meta tags such as titles and descriptions to help search engines understand the purpose of each page and improve how my site appears in search 
- Using Lazy Loading: I will implement lazy loading for images and components to enhance page load speed and user experience, These are essential factors for SEO improvement.

**Comment by SusheelThapa** [comment]
@Ujj1225 
It looks good, for now I don't have anything on my mind. 
If i have, I will update via comment in this issue

**Comment by SusheelThapa** [comment]
@P-stha12  favicon drop gardeu hai yo issue ma
Ani @Ujj1225  favicon in upload gara hai timile koleko PR ma

**Comment by SusheelThapa** [comment]
@Ujj1225  Any updates on this issue?

**Comment by SusheelThapa** [comment]
Use this for favicon: https://www.locus.com.np/assets/home/small_logo.png

**Comment by Ujj1225** [comment]
@SusheelThapa  I am almost done with my work. I'll push the code by tomorrow
